import { defineConfig, loadEnv, type Plugin } from 'vite';
import fs from 'fs';
import path from 'path';
import react from '@vitejs/plugin-react';
import svgr from 'vite-plugin-svgr';
import tailwindcss from '@tailwindcss/vite';
import nodePolyfills from 'vite-plugin-node-stdlib-browser';
import { VitePWA } from 'vite-plugin-pwa';

const browserPkg = JSON.parse(fs.readFileSync(
  path.resolve(__dirname, 'node_modules/@enbox/browser/package.json'), 'utf-8',
));
const browserVersion = browserPkg.version as string;

/**
 * Replaces `__PRODUCT_BRAND__` in index.html with the product brand slug so
 * static brand assets (e.g. the Open Graph image) follow the product accent:
 * `VITE_PRODUCT_THEME=blue` → blue assets, default → rose. The logo variants
 * are generated by `scripts/generate-brand-assets.mjs`.
 */
function productBrandPlugin(brand: string): Plugin {
  return {
    name: 'enbox-product-brand',
    transformIndexHtml(html) {
      return html.replaceAll('__PRODUCT_BRAND__', brand);
    },
  };
}

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '');
  const brand = env.VITE_PRODUCT_THEME === 'blue' ? 'blue' : 'rose';

  return {
    base: '/',
    resolve: {
      alias: {
        '@': path.resolve(__dirname, './src'),
      },
    },
    define: {
      global                          : 'globalThis',
      '__ENBOX_BROWSER_SDK_VERSION__' : JSON.stringify(browserVersion),
    },
    plugins: [
      tailwindcss(),
      svgr(),
      react(),
      nodePolyfills(),
      productBrandPlugin(brand),
      VitePWA({
        strategies: 'injectManifest',
        srcDir: 'src',
        filename: 'sw.ts',
        registerType: 'prompt',
        injectRegister: false,

        pwaAssets: {
          disabled: false,
          image: `public/logo-${brand}.svg`,
        },

        manifest: {
          name: 'Enbox Wallet',
          short_name: 'Enbox',
          description: 'Your digital identity wallet — manage DIDs, protocols, and encrypted data',
          theme_color: '#0a0a0f',
          background_color: '#0a0a0f',
        },

        injectManifest: {
          maximumFileSizeToCacheInBytes: 5_000_000,
          globPatterns: ['**/*.{js,css,html,json,svg,png,ico}'],
        },

        devOptions: {
          enabled: true,
          navigateFallback: 'index.html',
          suppressWarnings: false,
          type: 'module',
        },
      }),
    ],
    build: {
      chunkSizeWarningLimit: 3000,
      rollupOptions: {
        output: {
          manualChunks(id: string) {
            if (id.includes('node_modules')) {
              // Keep React framework in its own chunk
              if (
                id.includes('react-dom') ||
                id.includes('react-router') ||
                id.includes('/react/')
              )
                return 'vendor-react';
              // UI libraries (no circular deps with SDK)
              if (
                id.includes('@tanstack') ||
                id.includes('zustand') ||
                id.includes('sonner') ||
                id.includes('lucide') ||
                id.includes('clsx') ||
                id.includes('qrcode')
              )
                return 'vendor-ui';
              // Everything else (including @enbox/* and its transitive deps
              // like node-stdlib-browser, multiformats, etc.) stays in one
              // chunk to avoid circular-dependency initialisation errors.
            }
          },
        },
      },
    },
  };
});
