/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// SPA fallback: serve index.html for all navigation requests
const navigationHandler = async () => {
  const cache = await caches.open('workbox-precache-v2');
  const cachedResponse = await cache.match('/index.html');
  return cachedResponse || fetch('/index.html');
};

registerRoute(new NavigationRoute(navigationHandler));

// Activate Enbox browser polyfills (DRL fetch interception)
// This enables dweb:// URLs to be resolved via the service worker
// Wrapped in an IIFE to avoid top-level await (unsupported in SW build targets)
(async () => {
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const mod: any = await import('@enbox/browser');
    const { activatePolyfills } = mod;
    activatePolyfills({ injectStyles: false, links: false });
  } catch {
    // Polyfills not available -- not critical for wallet operation
  }
})();

// Listen for skip waiting messages
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
